project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Methoden"
  language: de
  reader-mode: true
  page-footer:
    left: |
      Quantitative Methoden
    center: |
      Made with ❤️ by [Lukas Batschelet](https://lukasbatschelet.ch/)
    right: |
      [☕️Buy me a coffee](https://www.buymeacoffee.com/lbatschelet)
  # cover-image: cover.jpg
  favicon: code
  site-url: https://quanti.baets.ch/
  repo-url: https://github.com/lbatschelet/quantitative_methoden
  issue-url: https://github.com/lbatschelet/quantitative_methoden/issues/new?assignees=lbatschelet&labels=bug%2C+enhancement&projects=&template=bug_report.md&title=%5BChapter%5D+Brief+description+of+the+issue+or+suggestion
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    tools:
      - icon: cup-hot-fill
        href: https://www.buymeacoffee.com/lbatschelet
        text: Buy me a coffee
  chapters:
    - index.qmd
    # - computer_basics_and_entry_to_R.qmd
    - grundlagen_R.qmd
    - plots_in_R.qmd
    - packages_and_libraries.qmd
    - loops_and_functions.qmd
    # - wichtige_funktionen.qmd


format:
  html:
    theme: cosmo
    number-depth: 4
