project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Methoden"
  language: de
  reader-mode: true
  page-footer:
    left: |
      Quantitative Methoden
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  # cover-image: cover.jpg
  # favicon: cover.jpg
  site-url: https://quanti.baets.ch/
  repo-url: https://github.com/lbatschelet/quantitative_methoden
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    # - computer_basics_and_entry_to_R.qmd
    - grundlagen_R.qmd
    - plots_in_R.qmd
    - packages_and_libraries.qmd
    - loops_and_functions.qmd
    # - wichtige_funktionen.qmd


format:
  html:
    theme: cosmo
    number-depth: 4
