<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de-CH" xml:lang="de-CH"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; LineareRegression – Quantitative Methoden</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./fehlermasse.html" rel="next">
<link href="./korrelation.html" rel="prev">
<link href="./code" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./deskriptive-statistik.html">Statistische Datenanalyse</a></li><li class="breadcrumb-item"><a href="./regression.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">LineareRegression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Methoden</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://ko-fi.com/lukasbatschelet" title="Buy me a coffee" class="quarto-navigation-tool px-1" aria-label="Buy me a coffee"><i class="bi bi-cup-hot-fill"></i></a>
    <a href="https://github.com/lbatschelet/quantitative_methoden" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Lesemodus umschalten">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Übersicht</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Einführung R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./grundlagen_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Grundlagen R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./plots_in_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einfache Plots erstellen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./packages_and_libraries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Packages und Libraries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./loops_and_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Schlaufen und Funktionen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistische Datenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./deskriptive-statistik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Deskriptive Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./verteilungen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Verteilungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistische-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Statistische Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./korrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">LineareRegression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fehlermasse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Fehlermasse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clusteranalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Clusteranalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hauptkomponentenanalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hauptkomponentenanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extremwertstatistik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Extremwertstatistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./neuronale-netze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Neuronale Netze</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fallen-der-statistik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Fallen der Statistik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glossar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Glossar</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./excercises/ex01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Übung 1: Grundlagen R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./excercises/ex02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">R-Übungen 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./excercises/ex03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">R-Übungen 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./excercises/deskriptive-statistik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Übung 4: Deskriptive Statistik und Visualisierung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./excercises/verteilungen-und-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Übung 5 &amp; 6: Verteilungen und Tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#einfache-lineare-regression" id="toc-einfache-lineare-regression" class="nav-link active" data-scroll-target="#einfache-lineare-regression"><span class="header-section-number">10.0.1</span> Einfache lineare Regression</a></li>
  <li><a href="#abweichungen-residuen" id="toc-abweichungen-residuen" class="nav-link" data-scroll-target="#abweichungen-residuen"><span class="header-section-number">10.0.2</span> Abweichungen (Residuen)</a></li>
  <li><a href="#bestimmung-der-modellgüte" id="toc-bestimmung-der-modellgüte" class="nav-link" data-scroll-target="#bestimmung-der-modellgüte"><span class="header-section-number">10.1</span> Bestimmung der Modellgüte</a>
  <ul class="collapse">
  <li><a href="#testen-der-signifikanz-der-regressionskoeffizienten" id="toc-testen-der-signifikanz-der-regressionskoeffizienten" class="nav-link" data-scroll-target="#testen-der-signifikanz-der-regressionskoeffizienten"><span class="header-section-number">10.1.1</span> Testen der Signifikanz der Regressionskoeffizienten</a></li>
  <li><a href="#berechnung-der-linearen-regression-in-r" id="toc-berechnung-der-linearen-regression-in-r" class="nav-link" data-scroll-target="#berechnung-der-linearen-regression-in-r"><span class="header-section-number">10.1.3</span> Berechnung der linearen Regression in R</a></li>
  </ul></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression"><span class="header-section-number">10.2</span> Multiple Regression</a>
  <ul class="collapse">
  <li><a href="#ziel" id="toc-ziel" class="nav-link" data-scroll-target="#ziel"><span class="header-section-number">10.2.1</span> Ziel:</a></li>
  <li><a href="#ansatz" id="toc-ansatz" class="nav-link" data-scroll-target="#ansatz"><span class="header-section-number">10.2.2</span> Ansatz</a></li>
  </ul></li>
  <li><a href="#anwendungsbedingungen" id="toc-anwendungsbedingungen" class="nav-link" data-scroll-target="#anwendungsbedingungen"><span class="header-section-number">10.3</span> Anwendungsbedingungen</a>
  <ul class="collapse">
  <li><a href="#lineare-beziehung-zwischen-den-variablen" id="toc-lineare-beziehung-zwischen-den-variablen" class="nav-link" data-scroll-target="#lineare-beziehung-zwischen-den-variablen"><span class="header-section-number">10.3.1</span> Lineare Beziehung zwischen den Variablen</a></li>
  <li><a href="#keine-perfekte-multikollinearität" id="toc-keine-perfekte-multikollinearität" class="nav-link" data-scroll-target="#keine-perfekte-multikollinearität"><span class="header-section-number">10.3.2</span> Keine perfekte Multikollinearität</a></li>
  <li><a href="#heteroskedastizität" id="toc-heteroskedastizität" class="nav-link" data-scroll-target="#heteroskedastizität"><span class="header-section-number">10.3.3</span> Heteroskedastizität</a></li>
  <li><a href="#normalverteilte-residuen" id="toc-normalverteilte-residuen" class="nav-link" data-scroll-target="#normalverteilte-residuen"><span class="header-section-number">10.3.4</span> Normalverteilte Residuen</a></li>
  <li><a href="#keine-starken-ausreißer-oder-einflussreichen-datenpunkte" id="toc-keine-starken-ausreißer-oder-einflussreichen-datenpunkte" class="nav-link" data-scroll-target="#keine-starken-ausreißer-oder-einflussreichen-datenpunkte"><span class="header-section-number">10.3.5</span> Keine starken Ausreißer oder einflussreichen Datenpunkte</a></li>
  <li><a href="#beispielauswertungen" id="toc-beispielauswertungen" class="nav-link" data-scroll-target="#beispielauswertungen"><span class="header-section-number">10.3.6</span> Beispielauswertungen</a></li>
  </ul></li>
  <li><a href="#modellvalidierung" id="toc-modellvalidierung" class="nav-link" data-scroll-target="#modellvalidierung"><span class="header-section-number">10.4</span> Modellvalidierung</a>
  <ul class="collapse">
  <li><a href="#kreuzvalidierung" id="toc-kreuzvalidierung" class="nav-link" data-scroll-target="#kreuzvalidierung"><span class="header-section-number">10.4.1</span> Kreuzvalidierung</a></li>
  <li><a href="#f-test" id="toc-f-test" class="nav-link" data-scroll-target="#f-test"><span class="header-section-number">10.4.2</span> F-Test</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/lbatschelet/quantitative_methoden/edit/main/regression.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/lbatschelet/quantitative_methoden/issues/new?assignees=lbatschelet&amp;labels=bug%2C+enhancement&amp;projects=&amp;template=bug_report.md&amp;title=%5BChapter%5D+Brief+description+of+the+issue+or+suggestion" class="toc-action"><i class="bi empty"></i>Problem melden</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./deskriptive-statistik.html">Statistische Datenanalyse</a></li><li class="breadcrumb-item"><a href="./regression.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">LineareRegression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">LineareRegression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Ziel:</strong></p>
<p>Vorhersage einer <strong>metrischen abhängigen Variable</strong> (auch <em>Zielvariable</em> oder <em>Kriterium</em>) durch eine oder mehrere <strong>unabhängige Variablen</strong> (auch <em>Prädiktoren</em> oder <em>Einflussgrössen</em>).</p>
<p><strong>Voraussetzungen:</strong></p>
<ul>
<li>Ein <em>statistischer Zusammenhang</em> zwischen Prädiktoren und Kriterium sollte plausibel sein.<br>
</li>
<li>Ein <em>Modell</em>, das die Abhängigkeit der Zielvariable von den Prädiktoren beschreibt.</li>
</ul>
<p>Bei einer Regressionsanalyse gibt es eine <em>abhängige Variable</em> (<span class="math inline">\(y\)</span>), die erklärt werden soll, und <em>eine oder mehrere unabhängige Variablen</em> (<span class="math inline">\(x_1, x_2, \dots, x_k\)</span>), die mit der Zielvariable in Verbindung stehen.</p>
<p>Die allgemeine Form der <strong>multiplen linearen Regression</strong> lautet:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k x_k + \varepsilon
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> ist die <em>Regressionskonstante</em> (Achsenabschnitt), also der geschätzte Wert für <span class="math inline">\(y\)</span>, wenn alle <span class="math inline">\(x_i = 0\)</span> sind.<br>
</li>
<li><span class="math inline">\(\beta_1, \beta_2, \dots, \beta_k\)</span> sind die <em>Regressionskoeffizienten</em>, die die Stärke des Zusammenhangs zwischen <span class="math inline">\(x_i\)</span> und <span class="math inline">\(y\)</span> beschreiben.<br>
</li>
<li><span class="math inline">\(\varepsilon\)</span> ist der <em>Fehlerterm</em>, der alle nicht erfassten Einflüsse auf <span class="math inline">\(y\)</span> berücksichtigt.</li>
</ul>
<p><strong>Interpretation der Regressionskoeffizienten</strong></p>
<ul>
<li>Wenn <span class="math inline">\(x_i\)</span> um <em>eine Einheit</em> steigt, verändert sich <span class="math inline">\(y\)</span> um <span class="math inline">\(\beta_i\)</span>, <em>unter der Annahme, dass alle anderen <span class="math inline">\(x_j\)</span> konstant bleiben</em>.<br>
</li>
<li>Beispiel: Wenn <span class="math inline">\(\beta_1 = 2\)</span>, dann bedeutet das, dass eine Erhöhung von <span class="math inline">\(x_1\)</span> um <em>eine Einheit</em> zu einer durchschnittlichen Erhöhung von <span class="math inline">\(y\)</span> um <em>2 Einheiten</em> führt.</li>
</ul>
<section id="einfache-lineare-regression" class="level3" data-number="10.0.1">
<h3 data-number="10.0.1" class="anchored" data-anchor-id="einfache-lineare-regression"><span class="header-section-number">10.0.1</span> Einfache lineare Regression</h3>
<p>Wir wollen eine Gerade der Form:</p>
<p><span class="math display">\[
\hat{y} = \beta_0 + \beta_{1x} x
\]</span></p>
<ul>
<li><span class="math inline">\(\hat{y}\)</span> = geschätzter Wert von <span class="math inline">\(y\)</span><br>
</li>
<li><span class="math inline">\(\beta_0\)</span> = <strong>Achsenabschnitt</strong> (Intercept)<br>
</li>
<li><span class="math inline">\(\beta_1\)</span> = <strong>Steigung</strong> der Regressionsgerade</li>
</ul>
<p>Die Parameter <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> bestimmen die Lage und Neigung der Regressionsgerade.</p>
</section>
<section id="abweichungen-residuen" class="level3" data-number="10.0.2">
<h3 data-number="10.0.2" class="anchored" data-anchor-id="abweichungen-residuen"><span class="header-section-number">10.0.2</span> Abweichungen (Residuen)</h3>
<p>Kein Modell beschreibt die Realität perfekt. Daher gibt es für jeden Datenpunkt eine <strong>Abweichung</strong> (Residuum) zu der Regressionsgerade:</p>
<p><span class="math display">\[
e_i = y_i - \hat{y}_i
\]</span></p>
<ul>
<li><span class="math inline">\(e_i\)</span> = Residuum des <span class="math inline">\(i\)</span>-ten Datenpunkts<br>
</li>
<li><span class="math inline">\(y_i\)</span> = tatsächlicher Wert<br>
</li>
<li><span class="math inline">\(\hat{y}_i\)</span> = durch das Modell geschätzter Wert</li>
</ul>
<p>Das Ziel der linearen Regression ist es, diese Abweichungen so klein wie möglich zu halten.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Beispiel">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wir betrachten die Daten aus <a href="korrelation.html#tbl-noten-lernzeit-beispiel" class="quarto-xref">Tabelle&nbsp;<span>9.1</span></a> und untersuchen den Zusammenhang zwischen Lernzeit (h/Woche, <span class="math inline">\(X\)</span>) und Prüfungsnote (<span class="math inline">\(Y\)</span>).</p>
<p><strong>1. Gegebene Werte</strong></p>
<p>Bereits bekannte Werte aus vorherigen Berechnungen:</p>
<ul>
<li><p><strong>Mittelwerte:</strong><br>
<span class="math inline">\(\bar{X} = 10\)</span> (<a href="korrelation.html#eq-noten-lernzeit-mittelwert-x" class="quarto-xref">Gleichung&nbsp;<span>9.2</span></a>), <span class="math inline">\(\bar{Y} = 70\)</span> (<a href="korrelation.html#eq-noten-lernzeit-mittelwert-y" class="quarto-xref">Gleichung&nbsp;<span>9.1</span></a>)</p></li>
<li><p><strong>Standardabweichungen:</strong><br>
<span class="math inline">\(\sigma_X = 3.81\)</span> (<a href="korrelation.html#eq-noten-lernzeit-standardabweichung-x" class="quarto-xref">Gleichung&nbsp;<span>9.5</span></a>), <span class="math inline">\(\sigma_Y = 15.81\)</span> (<a href="korrelation.html#eq-noten-lernzeit-standardabweichung-y" class="quarto-xref">Gleichung&nbsp;<span>9.4</span></a>)</p></li>
<li><p><strong>Kovarianz:</strong><br>
<span class="math inline">\(\text{Cov}(X, Y) = 60\)</span> (<a href="korrelation.html#eq-noten-lernzeit-kovarianz" class="quarto-xref">Gleichung&nbsp;<span>9.3</span></a>)</p></li>
<li><p><strong>Varianz von <span class="math inline">\(X\)</span>:</strong><br>
<span class="math inline">\(\sigma_X^2 = 14.5\)</span> ergibt sich aus <span class="math inline">\(\sigma_X\)</span></p></li>
</ul>
<p><strong>2. Berechnung der Regressionskoeffizienten</strong></p>
<ul>
<li>Steigung <span class="math inline">\(\beta_1\)</span></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
\beta_1 &amp;= \frac{\text{Cov}(X, Y)}{\sigma_X^2} \\
&amp;= \frac{60}{14.5} \\
&amp;\approx 4.14
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>noten_lernzeit_tabelle <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">student =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"E"</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">note =</span> <span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">80</span>, <span class="dv">50</span>, <span class="dv">90</span>, <span class="dv">60</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">lernzeit =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">5</span>, <span class="dv">15</span>, <span class="dv">8</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(note <span class="sc">~</span> lernzeit, <span class="at">data =</span> noten_lernzeit_tabelle)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model)[<span class="dv">2</span>]  <span class="co"># Zweites Element ist der Koeffizient für lernzeit</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>beta1</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lernzeit 
4.137931 </code></pre>
</div>
</div>
<p><span class="math inline">\(\Rightarrow\)</span> Jede zusätzliche Lernstunde pro Woche erhöht die erwartete Prüfungsnote um 4.14 Punkte.</p>
<ul>
<li>Achsenabschnitt <span class="math inline">\(\beta_0\)</span></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
\beta_0 &amp;= \bar{Y} - \beta_1 \bar{X} \\
&amp;\approx 70 - (4.14 \cdot 10) \\
&amp;\approx 70 - 41.4 \\
&amp;\approx 28.6
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model)[<span class="dv">1</span>]  <span class="co"># Erstes Element ist der Koeffizient für den Achsenabschnitt</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>beta0</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   28.62069 </code></pre>
</div>
</div>
<p><span class="math inline">\(\Rightarrow\)</span> Ohne Lernzeit (<span class="math inline">\(X = 0\)</span>) wäre die erwartete Note 28.6.</p>
<p><strong>3. Regressionsgleichung</strong></p>
<p><span class="math display">\[
\hat{Y} \approx 28.6 + 4.14 X
\]</span></p>
<p><strong>4. Vorhersagewerte <span class="math inline">\(\hat{Y}\)</span></strong></p>
<p>Die vorhergesagten Prüfungsnoten für unsere Lernzeiten:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 23%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Student</th>
<th><span class="math inline">\(X\)</span> (Lernzeit)</th>
<th><span class="math inline">\(Y\)</span> (Tatsächlich)</th>
<th><span class="math inline">\(\hat{Y}\)</span> (Vorhersage)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>10</td>
<td>70</td>
<td><span class="math inline">\(28.6 + 4.14 \cdot 10 \approx 70.0\)</span></td>
</tr>
<tr class="even">
<td>B</td>
<td>12</td>
<td>80</td>
<td><span class="math inline">\(28.6 + 4.14 \cdot 12 \approx 78.3\)</span></td>
</tr>
<tr class="odd">
<td>C</td>
<td>5</td>
<td>50</td>
<td><span class="math inline">\(28.6 + 4.14 \cdot 5 \approx 49.3\)</span></td>
</tr>
<tr class="even">
<td>D</td>
<td>15</td>
<td>90</td>
<td><span class="math inline">\(28.6 + 4.14 \cdot 15 \approx 90.7\)</span></td>
</tr>
<tr class="odd">
<td>E</td>
<td>8</td>
<td>60</td>
<td><span class="math inline">\(28.6 + 4.14 \cdot 8 \approx 61.7\)</span></td>
</tr>
</tbody>
</table>
<p>Wir sehen, dass die vorhergesagten Werte gut zu den tatsächlichen Werten passen.</p>
<p><strong>5. Berechnung der Residuen <span class="math inline">\(e_i\)</span></strong></p>
<p>Das Residuum ist die Differenz zwischen tatsächlichem Wert <span class="math inline">\(Y_i\)</span> und vorhergesagtem Wert <span class="math inline">\(\hat{Y}_i\)</span>:</p>
<p><span class="math display">\[
e_i = Y_i - \hat{Y}_i
\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 26%">
<col style="width: 33%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Student</th>
<th><span class="math inline">\(Y\)</span> (Tatsächlich)</th>
<th><span class="math inline">\(\hat{Y}\)</span> (Vorhersage)</th>
<th>Residuum <span class="math inline">\(e_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>70</td>
<td>70.0</td>
<td><span class="math inline">\(70 - 70 = 0.0\)</span></td>
</tr>
<tr class="even">
<td>B</td>
<td>80</td>
<td>78.3</td>
<td><span class="math inline">\(80 - 78.3 = 1.7\)</span></td>
</tr>
<tr class="odd">
<td>C</td>
<td>50</td>
<td>49.3</td>
<td><span class="math inline">\(50 - 49.3 = 0.7\)</span></td>
</tr>
<tr class="even">
<td>D</td>
<td>90</td>
<td>90.7</td>
<td><span class="math inline">\(90 - 90.7 = -0.7\)</span></td>
</tr>
<tr class="odd">
<td>E</td>
<td>60</td>
<td>61.7</td>
<td><span class="math inline">\(60 - 61.7 = -1.7\)</span></td>
</tr>
</tbody>
</table>
<p>Die Residuen sind klein, was bedeutet, dass die Regressionsgerade gut zu den Daten passt.</p>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Jede zusätzliche Lernstunde erhöht die erwartete Prüfungsnote um 4.14 Punkte.<br>
</li>
<li>Ohne zu lernen (wenn <span class="math inline">\(X = 0\)</span>), wäre die erwartete Note 28.6.</li>
</ul>
</div>
</div>
</section>
<section id="bestimmung-der-modellgüte" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="bestimmung-der-modellgüte"><span class="header-section-number">10.1</span> Bestimmung der Modellgüte</h2>
<p>Die Güte der Anpassung wird durch das <strong>Bestimmtheitsmass</strong> <span class="math inline">\(R^2\)</span> beurteilt. Dieses Mass gibt an, welcher Anteil der Gesamtvariation von <span class="math inline">\(Y\)</span> durch das Modell erklärt wird:</p>
<p><span class="math display">\[
R^2 = \frac{\text{erklärte Variation}}{\text{Gesamtvariation}} = 1 - \frac{\text{Residuenvariation}}{\text{Gesamtvariation}}
\]</span></p>
<p>Das bedeutet:</p>
<p><span class="math display">\[
R^2 = 1 - \frac{\sum_{i=1}^{n} (Y_i - \hat{Y}_i)^2}{\sum_{i=1}^{n} (Y_i - \bar{Y})^2}
\]</span></p>
<ul>
<li><span class="math inline">\(Y_i\)</span> ist der tatsächliche Wert der abhängigen Variablen.<br>
</li>
<li><span class="math inline">\(\hat{Y}_i\)</span> ist der vorhergesagte Wert der abhängigen Variablen.<br>
</li>
<li><span class="math inline">\(\bar{Y}\)</span> ist der Mittelwert von <span class="math inline">\(Y\)</span>.<br>
</li>
<li>Der Zähler beschreibt die <strong>Residuenvariation</strong> (nicht erklärte Abweichung).<br>
</li>
<li>Der Nenner beschreibt die <strong>Gesamtvariation</strong> (Gesamtstreuung der Daten).</li>
</ul>
<p><strong>Eigenschaften von <span class="math inline">\(R^2\)</span>:</strong></p>
<ul>
<li><span class="math inline">\(R^2\)</span> liegt <strong>immer zwischen 0 und 1</strong>.<br>
</li>
<li><span class="math inline">\(R^2 = 1\)</span> bedeutet <strong>perfekte Anpassung</strong> (alle Datenpunkte liegen exakt auf der Regressionsgeraden).<br>
</li>
<li><span class="math inline">\(R^2 = 0\)</span> bedeutet <strong>keine Anpassung</strong> (die unabhängige Variable erklärt nichts).</li>
</ul>
<section id="testen-der-signifikanz-der-regressionskoeffizienten" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="testen-der-signifikanz-der-regressionskoeffizienten"><span class="header-section-number">10.1.1</span> Testen der Signifikanz der Regressionskoeffizienten</h3>
<p>Um zu überprüfen, ob die unabhängige Variable tatsächlich einen <strong>signifikanten Einfluss auf <span class="math inline">\(Y\)</span></strong> hat, testen wir die Hypothesen:</p>
<ul>
<li><strong>Nullhypothese <span class="math inline">\(H_0\)</span>:</strong> Kein linearer Zusammenhang <span class="math inline">\(\Rightarrow \beta_1 = 0\)</span>.<br>
</li>
<li><strong>Alternativhypothese <span class="math inline">\(H_1\)</span>:</strong> Es gibt einen linearen Zusammenhang <span class="math inline">\(\Rightarrow \beta_1 \neq 0\)</span>.</li>
</ul>
<p>Da wir <span class="math inline">\(\beta_1\)</span> nicht direkt kennen, schätzen wir ihn mit <span class="math inline">\(\widehat{\beta}_1\)</span> und testen, ob dieser <strong>signifikant von 0 verschieden ist</strong>. Dafür berechnen wir die Teststatistik:</p>
<p><span class="math display">\[
T = \frac{\widehat{\beta}_1}{\operatorname{SE}_{\beta_1}}
\]</span></p>
<p>wobei der <strong>Standardfehler von <span class="math inline">\(\beta_1\)</span></strong> durch:</p>
<p><span class="math display">\[
\operatorname{SE}_{\beta_1} = \sqrt{\frac{\frac{1}{n-2} \sum_{i=1}^{n} (Y_i - \hat{Y}_i)^2}{\sum_{i=1}^{n} (X_i - \bar{X})^2}}
\]</span></p>
<p>gegeben ist.</p>
<ul>
<li><span class="math inline">\(T\)</span> folgt einer <strong>t-Verteilung mit <span class="math inline">\(n - 2\)</span> Freiheitsgraden</strong>, da wir die beiden Regressionskoeffizienten (<span class="math inline">\(\beta_0, \beta_1\)</span>) aus der Stichprobe schätzen.<br>
</li>
<li><strong>Wenn <span class="math inline">\(|T|\)</span> gross genug ist</strong>, lehnen wir <span class="math inline">\(H_0\)</span> ab → <strong><span class="math inline">\(X\)</span> hat einen signifikanten Einfluss auf <span class="math inline">\(Y\)</span></strong>.</li>
</ul>
<p><strong>Interpretation des Tests:</strong></p>
<ul>
<li>Falls der p-Wert kleiner als <span class="math inline">\(0.05\)</span> ist, lehnen wir <span class="math inline">\(H_0\)</span> ab. Es gibt <strong>einen signifikanten linearen Zusammenhang</strong>.<br>
</li>
<li>Falls der p-Wert grösser als <span class="math inline">\(0.05\)</span> ist, können wir <strong>keine signifikante Beziehung feststellen</strong>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Beispiel">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wir überprüfen die Signifikanz der Regressionskoeffizienten für das Beispiel der Lernzeit und der Prüfungsnote.</p>
<p><strong>1. Berechnung der Gesamtvariation <span class="math inline">\(SS_{total}\)</span></strong></p>
<p>Die Gesamtvariation ist die Summe der quadrierten Abweichungen jedes <span class="math inline">\(Y_i\)</span> vom Mittelwert <span class="math inline">\(\bar{Y}\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
SS_{\text{total}} &amp;= \sum_{i=1}^{n} (Y_i - \bar{Y})^2 \\
&amp;= \sum_{i=1}^{n} (70 - 70)^2 + (80 - 70)^2 + (50 - 70)^2 + (90 - 70)^2 + (60 - 70)^2 \\
&amp;= 0 + 100 + 400 + 400 + 100 \\
&amp;= 1000
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ss_total <span class="ot">&lt;-</span> <span class="fu">sum</span>((noten_lernzeit_tabelle<span class="sc">$</span>note <span class="sc">-</span> <span class="fu">mean</span>(noten_lernzeit_tabelle<span class="sc">$</span>note))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>ss_total</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1000</code></pre>
</div>
</div>
<p><strong>2. Berechnung der Residuenvariation <span class="math inline">\(SS_{residual}\)</span></strong></p>
<p>Die Residuenvariation ist die Summe der quadrierten Abweichungen der tatsächlichen Werte <span class="math inline">\(Y_i\)</span> von den vorhergesagten Werten <span class="math inline">\(\hat{Y}_i\)</span>, berechnet mit der Regressionsgleichung:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{Y}_i &amp;= 28.6 + 4.14 X_i \\
&amp;= 0^2 + 1.7^2 + 0.7^2 + (-0.7)^2 + (-1.7)^2 \\
&amp;\approx 0 + 2.89 + 0.49 + 0.49 + 2.89 \\
&amp;\approx 6.9
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ss_residual <span class="ot">&lt;-</span> <span class="fu">sum</span>(model<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ss_residual</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.896552</code></pre>
</div>
</div>
<section id="berechnung-des-bestimmtheitsmasses-r2" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="berechnung-des-bestimmtheitsmasses-r2"><span class="header-section-number">10.1.2</span> <strong>3. Berechnung des Bestimmtheitsmasses <span class="math inline">\(R^2\)</span></strong></h3>
<p>Nun setzen wir die Werte in die Formel ein:</p>
<p><span class="math display">\[
R^2 = 1 - \frac{SS_{\text{residual}}}{SS_{\text{total}}}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>r.squared</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>r_squared</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9931034</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{aligned}
R^2 &amp;\approx 1 - \frac{6.9}{1000} \\
&amp;\approx 1 - 0.0069 \\
&amp;\approx 0.993
\end{aligned}
\]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <strong>99.3% der Variation in den Prüfungsnoten wird durch die Lernzeit erklärt.</strong><br>
Das Modell passt also sehr gut zu den Daten.</p>
<p><strong>4. Berechnung des Standardfehlers von <span class="math inline">\(\beta_1\)</span></strong></p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{SE}_{\beta_1} &amp;= \sqrt{\frac{\frac{1}{n-2} \sum_{i=1}^{n} (Y_i - \hat{Y}_i)^2}{\sum_{i=1}^{n} (X_i - \bar{X})^2}} \\
&amp;= \sqrt{\frac{\frac{1}{3} \sum_{i=1}^{5} (Y_i - \hat{Y}_i)^2}{\sum_{i=1}^{5} (X_i - \bar{X})^2}} \\
&amp;= \sqrt{\frac{\frac{1}{3} \left[(70-70)^2 + (80-78.3)^2 + (50-49.3)^2 + (90-90.7)^2 + (60-61.7)^2\right]}{\left[(10-10)^2 + (12-10)^2 + (5-10)^2 + (15-10)^2 + (8-10)^2\right]}} \\
&amp;= \sqrt{\frac{\frac{1}{3} \left[0^2 + 1.7^2 + 0.7^2 + (-0.7)^2 + (-1.7)^2\right]}{\left[0^2 + 2^2 + (-5)^2 + 5^2 + (-2)^2\right]}} \\
&amp;= \sqrt{\frac{\frac{1}{3} \left[0 + 2.89 + 0.49 + 0.49 + 2.89\right]}{\left[0 + 4 + 25 + 25 + 4\right]}} \\
&amp;= \sqrt{\frac{\frac{1}{3} \left[6.76\right]}{58}} \\
&amp;\approx \sqrt{\frac{2.53}{58}} \\
&amp;\approx \sqrt{0.039} \\
&amp;\approx 0.197
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>se_beta1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coefficients[<span class="dv">2</span>, <span class="st">"Std. Error"</span>]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>se_beta1</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1990863</code></pre>
</div>
</div>
<p><strong>5. Berechnung der Teststatistik <span class="math inline">\(T\)</span></strong></p>
<p><span class="math display">\[
\begin{aligned}
T &amp;= \frac{\widehat{\beta}_1}{\operatorname{SE}_{\beta_1}} \\
&amp;= \frac{4.14}{0.197} \\
&amp;\approx 20.79
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>t_value <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(model))[<span class="dv">2</span>, <span class="st">"t value"</span>]</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>t_value</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20.78461</code></pre>
</div>
</div>
<p><strong>6. Berechnung des p-Werts</strong></p>
<p>Da die Teststatistik <span class="math inline">\(T\)</span> einer <strong>t-Verteilung mit <span class="math inline">\(n-2\)</span> Freiheitsgraden</strong> folgt, berechnen wir den <strong>p-Wert</strong> für den zweiseitigen Test:</p>
<p><span class="math display">\[
p = 2 \cdot P(T \geq |t_{\text{berechnet}}|)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coefficients[<span class="dv">2</span>, <span class="st">"Pr(&gt;|t|)"</span>]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>p_value</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0002435779</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Der berechnete p-Wert ist <strong>sehr klein</strong> <span class="math inline">\((p \approx 0.0002)\)</span>.</li>
<li>Da <span class="math inline">\(p &lt; 0.05\)</span>, können wir die <strong>Nullhypothese <span class="math inline">\(H_0\)</span> ablehnen</strong>.</li>
<li>Das bedeutet: <strong>Die Lernzeit hat einen signifikanten Einfluss auf die Prüfungsnote.</strong></li>
<li>Da der p-Wert sogar weit unter 0.001 liegt, ist der Zusammenhang <strong>hochsignifikant</strong>.</li>
</ul>
<p><strong>Fazit:</strong><br>
Die <strong>Regressionskoeffizienten sind signifikant</strong>. Es gibt <strong>starke Evidenz</strong>, dass eine höhere Lernzeit zu besseren Prüfungsnoten führt.</p>
</section>
</div>
</div>
<section id="konfidenzintervall-der-regressionskoeffizienten" class="level4" data-number="10.1.2.1">
<h4 data-number="10.1.2.1" class="anchored" data-anchor-id="konfidenzintervall-der-regressionskoeffizienten"><span class="header-section-number">10.1.2.1</span> Konfidenzintervall der Regressionskoeffizienten</h4>
<p><span class="math display">\[
\beta_1 = \widehat{\beta_1} \pm q_t \cdot \operatorname{SE}_{\beta_1} \quad \text{mit} \quad q_t \text{ aus der T-Tabelle}
\]</span></p>
<ul>
<li><span class="math inline">\(t_{n-2}\)</span> ist der kritische Wert der t-Verteilung mit <span class="math inline">\(n-2\)</span> Freiheitsgraden</li>
<li><span class="math inline">\(\operatorname{SE}_{\beta_1}\)</span> ist der Standardfehler der Steigung</li>
<li><span class="math inline">\(\widehat{\beta_1}\)</span> ist der geschätzte Regressionskoeffizient der Stichprobe</li>
</ul>
</section>
</section>
<section id="berechnung-der-linearen-regression-in-r" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="berechnung-der-linearen-regression-in-r"><span class="header-section-number">10.1.3</span> Berechnung der linearen Regression in R</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lineare Regression durchführen</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(note <span class="sc">~</span> lernzeit, <span class="at">data =</span> noten_lernzeit_tabelle)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>model</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = note ~ lernzeit, data = noten_lernzeit_tabelle)

Coefficients:
(Intercept)     lernzeit  
     28.621        4.138  </code></pre>
</div>
</div>
<p>Die Ausgabe der Funktion <code>lm()</code> zeigt uns:</p>
<ol type="1">
<li><strong>Call</strong>: Die verwendete Formel für die Regression
<ul>
<li><code>y ~ x</code> bedeutet: y wird durch x vorhergesagt</li>
</ul></li>
<li><strong>Coefficients</strong>: Die geschätzten Regressionskoeffizienten
<ul>
<li><strong>(Intercept)</strong>: <span class="math inline">\(\widehat{\beta_0}\)</span> = 28.621
<ul>
<li>Dies ist der y-Achsenabschnitt</li>
<li>Der vorhergesagte y-Wert, wenn x = 0</li>
</ul></li>
<li><strong>x</strong>: <span class="math inline">\(\widehat{\beta_1}\)</span> = 4.138
<ul>
<li>Dies ist die Steigung der Geraden</li>
<li>Für jede Einheit, die x zunimmt, steigt y um 4.138 Einheiten</li>
</ul></li>
</ul></li>
</ol>
<p>Für eine detailliertere Analyse können wir die Funktion <code>summary()</code> verwenden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = note ~ lernzeit, data = noten_lernzeit_tabelle)

Residuals:
         1          2          3          4          5 
-1.220e-14  1.724e+00  6.897e-01 -6.897e-01 -1.724e+00 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  28.6207     2.1032   13.61 0.000858 ***
lernzeit      4.1379     0.1991   20.79 0.000244 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.516 on 3 degrees of freedom
Multiple R-squared:  0.9931,    Adjusted R-squared:  0.9908 
F-statistic:   432 on 1 and 3 DF,  p-value: 0.0002436</code></pre>
</div>
</div>
<p>Die <code>summary()</code> zeigt uns zusätzlich:</p>
<ol type="1">
<li><strong>Residuals</strong>: Verteilung der Abweichungen zwischen vorhergesagten und tatsächlichen Werten
<ul>
<li>Minimum: -1.724</li>
<li>Maximum: 1.724</li>
<li>Die Quartile zeigen, wie die Residuen verteilt sind</li>
<li>Idealerweise symmetrisch um 0</li>
</ul></li>
<li><strong>Coefficients-Tabelle</strong>:
<ul>
<li><strong>Intercept</strong> (<span class="math inline">\(\widehat{\beta_0}\)</span> = 28.621):
<ul>
<li>Standardfehler: 2.103</li>
<li>t-Wert: 13.608</li>
<li>p-Wert: 0.001</li>
<li>Signifikant auf dem 0.1% Niveau</li>
</ul></li>
<li><strong>Steigung</strong> (<span class="math inline">\(\widehat{\beta_1}\)</span> = 4.138):
<ul>
<li>Standardfehler: 0.199</li>
<li>t-Wert: 20.785</li>
<li>p-Wert: 0</li>
<li>Signifikant auf dem 0.1% Niveau</li>
</ul></li>
</ul></li>
<li><strong>Modellgüte</strong>:
<ul>
<li><span class="math inline">\(R^2\)</span> = 0.993
<ul>
<li>99.3% der Varianz in y wird durch x erklärt</li>
</ul></li>
<li>Adjustiertes <span class="math inline">\(R^2\)</span> = 0.991
<ul>
<li>Berücksichtigt die Anzahl der Prädiktoren</li>
</ul></li>
</ul></li>
<li><strong>F-Test</strong>:
<ul>
<li>F-Wert: 432</li>
<li>Freiheitsgrade: 1 und 3</li>
<li>p-Wert: 2.4^{-4}</li>
<li>Das Modell ist statistisch signifikant</li>
</ul></li>
</ol>
</section>
</section>
<section id="multiple-regression" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="multiple-regression"><span class="header-section-number">10.2</span> Multiple Regression</h2>
<p>In der einfachen linearen Regression versuchen wir, den Zusammenhang zwischen einer abhängigen Variable <span class="math inline">\(Y\)</span> und einem Prädiktor <span class="math inline">\(X_1\)</span> zu modellieren. Doch was passiert, wenn <span class="math inline">\(Y\)</span> nicht vollständig durch <span class="math inline">\(X_1\)</span> alleine erklärt werden kann?</p>
<p>Stellen wir uns vor, wir haben Daten, bei denen wir vermuten, dass <span class="math inline">\(X_1\)</span> einen Einfluss auf <span class="math inline">\(Y\)</span> hat. Wir beginnen mit einer einfachen linearen Regression:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Daten simulieren</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="fl">1.5</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> X1 <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> X2 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Einfache lineare Regression Y ~ X1</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>model_X1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X1, Y, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">105</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">89</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">205</span><span class="sc">/</span><span class="dv">255</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>), </span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"X1"</span>, <span class="at">ylab =</span> <span class="st">"Y"</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model_X1, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/simple-regression-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Erste Regression: Y in Abhängigkeit von X1</figcaption>
</figure>
</div>
</div>
</div>
<p>Wir erkennen, dass <span class="math inline">\(X_1\)</span> einen deutlichen Einfluss auf <span class="math inline">\(Y\)</span> hat. Doch die Vorhersagen des Modells sind nicht perfekt – es bleiben <strong>Residuen</strong> übrig, also Abweichungen zwischen den tatsächlichen Werten von <span class="math inline">\(Y\)</span> und den durch das Modell prognostizierten Werten.</p>
<p>Diese Residuen sind nicht einfach nur zufälliges Rauschen. Sie könnten Hinweise darauf liefern, dass noch <strong>weitere Faktoren</strong> im Spiel sind, die wir bisher nicht berücksichtigt haben.</p>
<p>Um das zu überprüfen, untersuchen wir, ob ein weiterer Prädiktor <span class="math inline">\(X_2\)</span> möglicherweise einen Teil dieser unerklärten Varianz in <span class="math inline">\(Y\)</span> aufklären kann. Dazu betrachten wir die Residuen der ersten Regression und analysieren, ob sie mit <span class="math inline">\(X_2\)</span> zusammenhängen:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Berechne die Residuen der ersten Regression</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>residuals_X1 <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_X1)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression der Residuen auf X2</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>model_resid_X2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(residuals_X1 <span class="sc">~</span> X2)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X2, residuals_X1, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">105</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">89</span><span class="sc">/</span><span class="dv">255</span>, <span class="dv">205</span><span class="sc">/</span><span class="dv">255</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>), </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"X2"</span>, <span class="at">ylab =</span> <span class="st">"Residuen von Y ~ X1"</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model_resid_X2, <span class="at">col =</span> <span class="st">"orange"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/residual-regression-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Zweite Regression: Residuen von Y ~ X1 in Abhängigkeit von X2</figcaption>
</figure>
</div>
</div>
</div>
<p>Wir sehen, dass die Residuen tatsächlich einen Zusammenhang mit <span class="math inline">\(X_2\)</span> aufweisen. Das bedeutet, dass <span class="math inline">\(X_2\)</span> Varianz in <span class="math inline">\(Y\)</span> erklärt, die nicht durch <span class="math inline">\(X_1\)</span> erfasst wurde.</p>
<p>Man könnte diesen Prozess theoretisch weiterführen: Nachdem wir den Einfluss von <span class="math inline">\(X_2\)</span> modelliert haben, könnten wir die neuen Residuen betrachten und versuchen, diese durch einen weiteren Prädiktor <span class="math inline">\(X_3\)</span> zu erklären. Und so weiter.</p>
<p>Dieses schrittweise Vorgehen wirft jedoch ein Problem auf: Was passiert, wenn <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, …, <span class="math inline">\(X_k\)</span> miteinander korrelieren?</p>
<ul>
<li>In diesem Fall ist es schwierig, die individuellen Effekte der einzelnen Prädiktoren zu isolieren.</li>
<li>Der Einfluss von <span class="math inline">\(X_2\)</span> könnte bereits teilweise in der ersten Regression durch <span class="math inline">\(X_1\)</span> berücksichtigt worden sein – und umgekehrt.</li>
<li>Durch das schrittweise Vorgehen riskieren wir, <em>Doppelerklärungen</em> oder <em>verzerrte Effekte</em> zu erhalten.</li>
</ul>
<p>Wir brauchen einen Ansatz, der es uns ermöglicht, den Einfluss mehrerer Prädiktoren <em>gleichzeitig</em> zu berücksichtigen.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Beispiel">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Wir versuchen, den Abfluss eines Gebirgsbachs zu modellieren.</p>
<ul>
<li><span class="math inline">\(Y\)</span>: Abfluss</li>
<li><span class="math inline">\(X_1\)</span>: Schneeschmelze</li>
<li><span class="math inline">\(X_2\)</span>: Niederschlag</li>
</ul>
<p>Wenn wir den Abfluss <span class="math inline">\(Y\)</span> zunächst in Abhängigkeit von der Schneeschmelze <span class="math inline">\(X_1\)</span> modellieren, stellen wir fest, dass ein Teil der Varianz von <span class="math inline">\(Y\)</span> nicht erklärt wird. Wir vermuten, dass der Niederschlag <span class="math inline">\(X_2\)</span> einen zusätzlichen Einfluss haben könnte. Also modellieren wir die Residuen aus der ersten Regression in Abhängigkeit von <span class="math inline">\(X_2\)</span>.</p>
<p>Doch hier entsteht ein Problem: <em>Schneeschmelze und Niederschlag sind oft korreliert.</em> Nach starken Niederschlägen folgt häufig eine beschleunigte Schneeschmelze. Wenn wir <span class="math inline">\(X_2\)</span> nur auf die Residuen von <span class="math inline">\(X_1\)</span> anwenden, übersehen wir möglicherweise den gemeinsamen Einfluss beider Faktoren.</p>
<p>Das führt zu verzerrten Ergebnissen, da der Niederschlag sowohl einen direkten Einfluss auf den Abfluss hat als auch indirekt über die Schneeschmelze wirkt.</p>
</div>
</div>
</div>
<p><strong>Bemerkung:</strong> Wenn die Prädiktoren <em>nicht</em> korrelieren, ist die Regression der Residuen mit weiteren Variablen möglich.</p>
<section id="ziel" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="ziel"><span class="header-section-number">10.2.1</span> Ziel:</h3>
<p>Vorhersage einer <strong>metrischen abhängigen Variable</strong> durch mehrere <strong>unabhängige Variablen</strong> (<em>Prädiktoren</em>).</p>
<p><strong>Voraussetzungen:</strong></p>
<ul>
<li>Ein <strong>statistischer Zusammenhang</strong> zwischen den Prädiktoren und der Zielvariable sollte plausibel sein.<br>
</li>
<li>Ein <strong>Modell</strong>, das die Abhängigkeit der Zielvariable von den Prädiktoren beschreibt.</li>
</ul>
<p>Die allgemeine Form der <strong>multiplen linearen Regression</strong> lautet:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \ldots + \beta_k X_k + \varepsilon
\]</span></p>
<ul>
<li><span class="math inline">\(Y\)</span> ist die abhängige Variable.<br>
</li>
<li><span class="math inline">\(X_1, X_2, \ldots, X_k\)</span> sind die unabhängigen Variablen (<em>Prädiktoren</em>).<br>
</li>
<li><span class="math inline">\(\beta_0\)</span> ist die <em>Regressionskonstante</em> (Achsenabschnitt).<br>
</li>
<li><span class="math inline">\(\beta_1, \beta_2, \ldots, \beta_k\)</span> sind die <em>Regressionskoeffizienten</em>, die den Einfluss der jeweiligen Prädiktoren auf <span class="math inline">\(Y\)</span> beschreiben.<br>
</li>
<li><span class="math inline">\(\varepsilon\)</span> ist der <em>Fehlerterm</em>, der alle nicht erfassten Einflüsse berücksichtigt.</li>
</ul>
<p><strong>Interpretation der Regressionskoeffizienten</strong></p>
<ul>
<li>Wenn <span class="math inline">\(X_i\)</span> um <em>eine Einheit</em> steigt, verändert sich <span class="math inline">\(Y\)</span> um <span class="math inline">\(\beta_i\)</span>, <strong>unter der Annahme, dass alle anderen Prädiktoren konstant bleiben</strong>.<br>
</li>
<li>Beispiel: Wenn <span class="math inline">\(\beta_1 = 2\)</span>, dann bedeutet das, dass eine Erhöhung von <span class="math inline">\(X_1\)</span> um <em>eine Stunde Lernzeit</em> zu einer durchschnittlichen Erhöhung der Prüfungsnote um <em>2 Punkte</em> führt.</li>
</ul>
</section>
<section id="ansatz" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="ansatz"><span class="header-section-number">10.2.2</span> Ansatz</h3>
<ul>
<li>Minimierung der Summe der quadrierten Residuen:</li>
</ul>
<p><span class="math display">\[
\sum_{i=1}^{n} (Y_i - \widehat{\beta_0} - \widehat{\beta_1} X_{1i} - \widehat{\beta_2} X_{2i} - \ldots - \widehat{\beta_k} X_{ki})^2 \quad \rightarrow \quad \text{minimal}
\]</span></p>
<ul>
<li>Dafür müssen die partiellen Ableitungen nach allen <span class="math inline">\(\beta_j\)</span> gleich null gesetzt werden</li>
<li>Koeffizienten der multiplen Regression werden auch “partielle Regressionskoeffizienten” genannt</li>
</ul>
<p><span class="math display">\[
\widehat{Y_i} = \widehat{\beta_0} + \widehat{\beta_1} X_{1i} + \widehat{\beta_2} X_{2i} + \ldots + \widehat{\beta_k} X_{ki}
\]</span></p>
<p>oder in Matrixnotation:</p>
<p><span class="math display">\[
\widehat{Y} = X \widehat{\beta} \quad \text{mit} \quad \widehat{Y} = \begin{bmatrix} \widehat{Y_1} \\ \widehat{Y_2} \\ \vdots \\ \widehat{Y_n} \end{bmatrix}, \quad \widehat{\beta} = \begin{bmatrix} \widehat{\beta_0} \\ \widehat{\beta_1} \\ \vdots \\ \widehat{\beta_k} \end{bmatrix} \quad \text{und} \quad X = \begin{bmatrix} 1 &amp; X_{11} &amp; X_{21} &amp; \ldots &amp; X_{k1} \\ 1 &amp; X_{12} &amp; X_{22} &amp; \ldots &amp; X_{k2} \\ \vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\ 1 &amp; X_{1n} &amp; X_{2n} &amp; \ldots &amp; X_{kn} \end{bmatrix}
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Beispiel">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p>Da die Berechnung einer multiplen Regression sehr komplex ist, verwenden wir hierfür R und verzichten auf die manuelle Berechnung.</p>
</blockquote>
<p>Wir verwenden die Daten aus <a href="korrelation.html#tbl-noten-lernzeit-beispiel" class="quarto-xref">Tabelle&nbsp;<span>9.1</span></a> und ergänzen sie um zwei weitere Prädiktoren: <strong>Schlafdauer</strong> und <strong>Kaffeekonsum</strong>.</p>
<div id="tbl-noten-multiple-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-noten-multiple-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;10.1
</figcaption>
<div aria-describedby="tbl-noten-multiple-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 22%">
<col style="width: 30%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Student</th>
<th>Lernzeit <span class="math inline">\(X_1\)</span></th>
<th>Schlafdauer <span class="math inline">\(X_2\)</span></th>
<th>Kaffee <span class="math inline">\(X_3\)</span></th>
<th>Prüfungsnote <span class="math inline">\(Y\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>10</td>
<td>7.5</td>
<td>2</td>
<td>70</td>
</tr>
<tr class="even">
<td>B</td>
<td>12</td>
<td>6.5</td>
<td>3</td>
<td>80</td>
</tr>
<tr class="odd">
<td>C</td>
<td>5</td>
<td>6.0</td>
<td>0</td>
<td>50</td>
</tr>
<tr class="even">
<td>D</td>
<td>15</td>
<td>8.5</td>
<td>5</td>
<td>90</td>
</tr>
<tr class="odd">
<td>E</td>
<td>8</td>
<td>8.0</td>
<td>1</td>
<td>60</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>1. Regressionsmodell aufstellen</strong></p>
<p>Wir schätzen die folgende multiple lineare Regression:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + \varepsilon
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>noten_lernzeit_schlaf_kaffee <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">student =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"E"</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">lernzeit =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">5</span>, <span class="dv">15</span>, <span class="dv">8</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">schlafdauer =</span> <span class="fu">c</span>(<span class="fl">7.5</span>, <span class="fl">6.5</span>, <span class="fl">6.0</span>, <span class="fl">8.5</span>, <span class="fl">8.0</span>),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">kaffee =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">5</span>, <span class="dv">1</span>),</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">note =</span> <span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">80</span>, <span class="dv">50</span>, <span class="dv">90</span>, <span class="dv">60</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple lineare Regression durchführen</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(note <span class="sc">~</span> lernzeit <span class="sc">+</span> schlafdauer <span class="sc">+</span> kaffee, <span class="at">data =</span> noten_lernzeit_schlaf_kaffee)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Ergebnisse anzeigen</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multiple)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = note ~ lernzeit + schlafdauer + kaffee, data = noten_lernzeit_schlaf_kaffee)

Residuals:
      1       2       3       4       5 
 0.2626 -0.1050  0.0105 -0.0105 -0.1576 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  36.8067     1.9959  18.441   0.0345 *
lernzeit      4.5273     0.3028  14.951   0.0425 *
schlafdauer  -1.5756     0.1960  -8.041   0.0788 .
kaffee       -0.2626     0.5926  -0.443   0.7345  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3241 on 1 degrees of freedom
Multiple R-squared:  0.9999,    Adjusted R-squared:  0.9996 
F-statistic:  3173 on 3 and 1 DF,  p-value: 0.01305</code></pre>
</div>
</div>
<p><strong>2. Berechnung der Regressionskoeffizienten</strong></p>
<p>Die geschätzte <strong>Regressionsgleichung</strong> lautet:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{Y} &amp;= \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 \\
       &amp;\approx 36.8 + 4.53 X_1 + (-1.58) X_2 + (- 0.26) X_3
\end{aligned}
\]</span></p>
<p><strong>Interpretation:</strong></p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> (Lernzeit) ist erwartungsgemäss positiv und signifikant (p &lt; 0.05).<br>
</li>
<li><span class="math inline">\(\beta_2\)</span> (Schlafdauer) zeigt einen leichten negativen Effekt, mit knapp über unserem Signifikanzniveau von 0.05 (p &lt; 0.1)<br>
</li>
<li><span class="math inline">\(\beta_3\)</span> (Kaffeekonsum) ist leicht negativ, zeigt aber keinen signifikanten Zusammenhang (p &gt; 0.05).</li>
</ul>
<p><strong>3. Modellgüte und Vorhersagekraft</strong></p>
<p>Das <strong>Bestimmtheitsmaß</strong> <span class="math inline">\(R^2\)</span> gibt an, wie gut unser Modell die Prüfungsnoten erklärt:</p>
<p><span class="math display">\[
R^2 = 1 - \frac{SS_{\text{residual}}}{SS_{\text{total}}}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multiple)<span class="sc">$</span>r.squared</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.999895</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Mit <span class="math inline">\(R^2 =\)</span> 1 sehen wir, dass das unser Modell äusserst gut zu den Daten passt.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="anwendungsbedingungen" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="anwendungsbedingungen"><span class="header-section-number">10.3</span> Anwendungsbedingungen</h2>
<section id="lineare-beziehung-zwischen-den-variablen" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="lineare-beziehung-zwischen-den-variablen"><span class="header-section-number">10.3.1</span> Lineare Beziehung zwischen den Variablen</h3>
<p>Die lineare Regression setzt voraus, dass der Zusammenhang zwischen der abhängigen Variable (<span class="math inline">\(Y\)</span>) und den Prädiktoren (<span class="math inline">\(X_1, X_2, \dots, X_k\)</span>) <strong>linear</strong> ist.<br>
- In einem <strong>Scatterplot</strong> sollte eine ungefähr <strong>geradlinige Beziehung</strong> zwischen den Variablen erkennbar sein.<br>
- Falls ein nichtlinearer Zusammenhang vorliegt, kann eine <strong>Transformation</strong> der Variablen (z.B. logarithmisch oder quadratisch) sinnvoll sein.</p>
</section>
<section id="keine-perfekte-multikollinearität" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="keine-perfekte-multikollinearität"><span class="header-section-number">10.3.2</span> Keine perfekte Multikollinearität</h3>
<p>Kollinearität beschreibt die Tatsache, dass zwei oder mehrere Prädiktoren in einem Regressionsmodell stark miteinander korrelieren.</p>
<ul>
<li>Die unabhängigen Variablen dürfen untereinander nicht perfekt korrelieren (<span class="math inline">\(i \neq j: \text{corr}(X_i, X_j) = 1\)</span>) d.h. es darf keine Linearkombination anderer unabhängiger Variablen sein.</li>
<li>Matrix ist sonst nicht invertierbar.</li>
</ul>
<p>Folgen:</p>
<ul>
<li>Schätzungen der Regressionsparameter sind unzuverlässig</li>
<li>Standardfehler der Regressionskoeffizienten sind gross</li>
<li>t-Werte sind klein</li>
</ul>
<p>Anzeichen:</p>
<ul>
<li>Resultate werden stark vom Weglassen einer Beobachtung beeinflusst</li>
<li>Vorzeichen der Regressionskoeffizienten ist anders als erwartet</li>
<li>Hohe Korrelationen der unabhängigen Variablen (<span class="math inline">\(&gt; |0.8|\)</span>) deuten auf mögliche Kollinearität hin</li>
<li><strong>Varianzinflationsfaktor</strong> (VIF) misst die Abhängigkeit der Varianz des geschätzten Regressionskoeffizienten aufgrund der Korrelation zwischen unabhängigen Variablen. VIF-Werte <span class="math inline">\(&gt; 10\)</span> gelten als kritisch.
<ul>
<li><code>vif()</code></li>
</ul></li>
</ul>
<p>Behandlung:</p>
<ul>
<li>Weglassen von korrelierenden Prädiktoren</li>
<li>Neue Prädiktoren finden</li>
<li>Hauptkomponentenanalyse (PCA): Reduktion der Dimensionalität der Daten durch PCA, um unkorrelierte Hauptkomponenten zu erhalten.</li>
</ul>
</section>
<section id="heteroskedastizität" class="level3" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="heteroskedastizität"><span class="header-section-number">10.3.3</span> Heteroskedastizität</h3>
<p>Heteroskedastizität beschreibt die Tatsache, dass die Varianz der Residuen nicht konstant ist. Das bedeutet, dass die Residuen nicht gleichmässig um den Mittelwert streuen, sondern eine zunehmende oder abnehmende Varianz aufweisen.</p>
<p>Ursachen dafür können sein:</p>
<ul>
<li>Messfehler werden über die Zeit kleiner</li>
<li>Befragungen vor und nach dem Lernprozess</li>
<li>Verhalten ist abhängig vom Einkommen, so dass reichere Personen mehr Wahlmöglichkeiten haben als ärmere</li>
<li>Bei aggregierten Werten sind Klassen mit kleinem <span class="math inline">\(n\)</span> unsicherer und streuen mehr als Klassen mit grossem <span class="math inline">\(n\)</span></li>
</ul>
<p>Tests:</p>
<ul>
<li>Zerlegung der Daten und Vergleich von Subsets (z.B. Zeitperioden)</li>
<li>Goldfeld-Quandt-Test (univariate Regression)</li>
<li>White-Test (multiple Regression)</li>
</ul>
<p>Behandlung:</p>
<ul>
<li>Methode der <em>gewichteten</em> kleinsten Quadrate. Werte bekommen dort weniger Gewicht, wo die Streuung gross ist.</li>
</ul>
</section>
<section id="normalverteilte-residuen" class="level3" data-number="10.3.4">
<h3 data-number="10.3.4" class="anchored" data-anchor-id="normalverteilte-residuen"><span class="header-section-number">10.3.4</span> Normalverteilte Residuen</h3>
<p>Die Verteilung der Residuen sollte <strong>ungefähr normal</strong> sein. Dies ist besonders wichtig für:</p>
<ul>
<li><strong>t-Tests</strong> auf die Regressionskoeffizienten<br>
</li>
<li><strong>F-Tests</strong> zur Bewertung der Modellgüte<br>
</li>
<li><strong>Konfidenzintervalle für die <span class="math inline">\(\beta\)</span>-Koeffizienten</strong></li>
</ul>
<p>Ein <strong>Q-Q-Plot</strong> kann helfen, die Normalverteilung der Residuen zu überprüfen.</p>
<p>Falls die Residuen nicht normalverteilt sind:</p>
<ul>
<li><strong>Transformation</strong> der abhängigen Variable<br>
</li>
<li><strong>Bootstrapping-Verfahren</strong> zur Schätzung der Koeffizienten</li>
</ul>
</section>
<section id="keine-starken-ausreißer-oder-einflussreichen-datenpunkte" class="level3" data-number="10.3.5">
<h3 data-number="10.3.5" class="anchored" data-anchor-id="keine-starken-ausreißer-oder-einflussreichen-datenpunkte"><span class="header-section-number">10.3.5</span> Keine starken Ausreißer oder einflussreichen Datenpunkte</h3>
<p>Einzelne Datenpunkte mit <strong>extremen Werten</strong> können die Regression stark beeinflussen.</p>
<ul>
<li><strong>Leverage-Plot</strong> oder <strong>Cook’s Distance</strong> kann verwendet werden, um einflussreiche Punkte zu identifizieren.<br>
</li>
<li>Falls ein Ausreißer zu stark ist, sollte überprüft werden, ob ein <strong>Messfehler</strong> vorliegt oder ob der Punkt sinnvoll entfernt werden kann.</li>
</ul>
</section>
<section id="beispielauswertungen" class="level3" data-number="10.3.6">
<h3 data-number="10.3.6" class="anchored" data-anchor-id="beispielauswertungen"><span class="header-section-number">10.3.6</span> Beispielauswertungen</h3>
<section id="optimale-residuendiagnostik-mit-geeigneten-daten" class="level4" data-number="10.3.6.1">
<h4 data-number="10.3.6.1" class="anchored" data-anchor-id="optimale-residuendiagnostik-mit-geeigneten-daten"><span class="header-section-number">10.3.6.1</span> Optimale Residuendiagnostik mit geeigneten Daten</h4>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27" data-cap-location="top"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Synthetische Daten perfekt simulieren</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">2</span>)    <span class="co"># Normalverteilte Prädiktoren</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="fl">1.5</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">scale</span>(X1, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">scale</span>(X2, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Perfekte lineare Beziehung</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Fehler sind normalverteilt mit konstanter Varianz</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>errors <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)  <span class="co"># Normalverteilte Residuen</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Lineares Modell</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> X1 <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> X2 <span class="sc">+</span> errors</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Lineares Regressionsmodell</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>perfektes_modell <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagnostische Plots</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>dot_color <span class="ot">&lt;-</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.5</span>)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perfektes_modell, <span class="at">col =</span> dot_color, <span class="at">pch =</span> <span class="dv">19</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell fig-cap-location-top quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/multiple-regression-residuals-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Linearität: Die Residuen streuen zufällig um die Nulllinie. Kein systematisches Muster erkennbar – ein Hinweis auf eine lineare Beziehung.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/multiple-regression-residuals-plot-2.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Normalverteilung der Residuen: Die Punkte liegen nahe der Diagonale im Q-Q-Plot. Dies zeigt, dass die Residuen normalverteilt sind.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/multiple-regression-residuals-plot-3.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Varianzhomogenität: Die Punkte im Scale-Location-Plot sind gleichmässig verteilt, ohne Trichterform. Das deutet auf konstante Varianz (Homoskedastizität) hin.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/multiple-regression-residuals-plot-4.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Ausreisser: Im Leverage-Plot gibt es keine Punkte mit hoher Cook’s Distance. Dies zeigt, dass es keine einflussreichen Ausreisser gibt.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="negative-residuendiagnostik-mit-schlechten-daten" class="level4" data-number="10.3.6.2">
<h4 data-number="10.3.6.2" class="anchored" data-anchor-id="negative-residuendiagnostik-mit-schlechten-daten"><span class="header-section-number">10.3.6.2</span> Negative Residuendiagnostik mit schlechten Daten</h4>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28" data-cap-location="top"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Nicht-Linearität</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>X_nl <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>Y_nl <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> X_nl<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>modell_nl <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y_nl <span class="sc">~</span> X_nl)  <span class="co"># Falsch spezifiziert (linear)</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Nicht-normalverteilte Residuen</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>X_nn <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>Y_nn <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> X_nn <span class="sc">+</span> <span class="fu">rexp</span>(n, <span class="at">rate =</span> <span class="dv">1</span>)  <span class="co"># Exponentiell verteilte Fehler</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>modell_nn <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y_nn <span class="sc">~</span> X_nn)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Heteroskedastizität</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>X_het <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>Y_het <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">*</span> X_het <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="at">sd =</span> <span class="fu">abs</span>(X_het) <span class="sc">*</span> <span class="dv">2</span>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>modell_het <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y_het <span class="sc">~</span> X_het)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Ausreisser</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>X_out <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>Y_out <span class="ot">&lt;-</span> <span class="dv">5</span> <span class="sc">*</span> X_out <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>Y_out[<span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">100</span>)] <span class="ot">&lt;-</span> Y_out[<span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">100</span>)] <span class="sc">+</span> <span class="dv">20</span>  <span class="co"># Ausreisser hinzufügen</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>modell_out <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y_out <span class="sc">~</span> X_out)</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagnostische Plots (jeweils der relevante)</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modell_nl, <span class="at">which =</span> <span class="dv">1</span>, <span class="at">col =</span> dot_color, <span class="at">pch =</span> <span class="dv">19</span>)   <span class="co"># Nicht-Linearität: Residuals vs Fitted</span></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modell_nn, <span class="at">which =</span> <span class="dv">2</span>, <span class="at">col =</span> dot_color, <span class="at">pch =</span> <span class="dv">19</span>)   <span class="co"># Nicht-normalverteilte Residuen: Q-Q-Plot</span></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modell_het, <span class="at">which =</span> <span class="dv">3</span>, <span class="at">col =</span> dot_color, <span class="at">pch =</span> <span class="dv">19</span>)  <span class="co"># Heteroskedastizität: Scale-Location</span></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modell_out, <span class="at">which =</span> <span class="dv">5</span>, <span class="at">col =</span> dot_color, <span class="at">pch =</span> <span class="dv">19</span>)  <span class="co"># Ausreisser: Residuals vs Leverage</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell fig-cap-location-top quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/negative-regression-diagnostics-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Nicht-Linearität: Die Residuen zeigen ein gebogenes Muster. Dies deutet darauf hin, dass das Modell die wahre Beziehung nicht korrekt abbildet.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/negative-regression-diagnostics-2.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Nicht-Normalverteilte Residuen: Im Q-Q-Plot weichen die Punkte deutlich von der Diagonalen ab. Dies deutet auf eine Verletzung der Normalverteilungsannahme hin.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/negative-regression-diagnostics-3.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Heteroskedastizität: Im Scale-Location-Plot ist ein trichterförmiges Muster zu erkennen. Dies weist auf eine zunehmende Varianz der Residuen hin.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/negative-regression-diagnostics-4.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Ausreisser: Im Residuals vs Leverage-Plot sind Punkte mit hoher Cook’s Distance sichtbar. Sie haben einen starken Einfluss auf das Modell.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="modellvalidierung" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="modellvalidierung"><span class="header-section-number">10.4</span> Modellvalidierung</h2>
<section id="kreuzvalidierung" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="kreuzvalidierung"><span class="header-section-number">10.4.1</span> Kreuzvalidierung</h3>
<p>Die <strong>Kreuzvalidierung</strong> ist eine Methode zur <strong>Bewertung der Vorhersagegüte</strong> eines Regressionsmodells. Dabei wird der Datensatz in mehrere Teilmengen (sogenannte <strong>Folds</strong>) aufgeteilt. Das Modell wird wiederholt auf verschiedenen Kombinationen von Trainings- und Testdaten geschätzt, um zu überprüfen, wie gut es auf <strong>unbekannte Daten</strong> generalisiert.</p>
<section id="vorgehensweise-bei-der-k-fold-kreuzvalidierung" class="level4" data-number="10.4.1.1">
<h4 data-number="10.4.1.1" class="anchored" data-anchor-id="vorgehensweise-bei-der-k-fold-kreuzvalidierung"><span class="header-section-number">10.4.1.1</span> Vorgehensweise bei der K-Fold-Kreuzvalidierung:</h4>
<ol type="1">
<li><strong>Aufteilung der Daten:</strong> Der Datensatz wird in <span class="math inline">\(k\)</span> gleich grosse Teilmengen (Folds) aufgeteilt.<br>
</li>
<li><strong>Modelltraining:</strong> In jeder der <span class="math inline">\(k\)</span> Iterationen wird das Modell mit <span class="math inline">\((k-1)\)</span> Folds trainiert.<br>
</li>
<li><strong>Modelltest:</strong> Der verbliebene Fold dient als Testdatensatz zur Bewertung des Modells.<br>
</li>
<li><strong>Ergebnissynthese:</strong> Die Gütekriterien (z.B. <strong>mittlerer quadratischer Fehler</strong> (MSE), <strong><span class="math inline">\(R^2\)</span></strong>) werden über alle Iterationen gemittelt.</li>
</ol>
<p>Diese Methode liefert eine <strong>robustere Schätzung</strong> der Modellgüte als eine einfache Trainings-Test-Aufteilung.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel einer Multiplen Regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>In diesem Beispiel verwenden wir den Datensatz <code>mtcars</code>, um ein <strong>multiples lineares Regressionsmodell</strong> zu erstellen. Unser Ziel ist es, den <strong>Benzinverbrauch</strong> (<code>mpg</code>) von Fahrzeugen basierend auf mehreren Einflussgrössen vorherzusagen.</p>
<section id="datensatz-und-ziel" class="level5">
<h5 class="anchored" data-anchor-id="datensatz-und-ziel">Datensatz und Ziel</h5>
<ul>
<li><strong>Datensatz:</strong> <code>mtcars</code> mit 32 Fahrzeugen<br>
</li>
<li><strong>Zielvariable:</strong> <code>mpg</code> (Miles per Gallon, Benzinverbrauch)<br>
</li>
<li><strong>Prädiktoren:</strong>
<ul>
<li><code>wt</code> (Gewicht des Fahrzeugs in 1000 Pfund)<br>
</li>
<li><code>hp</code> (Motorleistung in PS)<br>
</li>
<li><code>cyl</code> (Anzahl Zylinder)</li>
</ul></li>
</ul>
<p>Wir möchten überprüfen, wie gut diese Variablen den Benzinverbrauch gemeinsam vorhersagen.</p>
</section>
<section id="durchführung-der-5-fold-kreuzvalidierung" class="level5">
<h5 class="anchored" data-anchor-id="durchführung-der-5-fold-kreuzvalidierung">Durchführung der 5-Fold-Kreuzvalidierung</h5>
<p>Für die <strong>5-Fold-Kreuzvalidierung</strong> wird der Datensatz in 5 gleich grosse Teilmengen (Folds) aufgeteilt. In jeder der 5 Iterationen wird das Modell mit 4 Folds trainiert und mit dem verbleibenden Fold getestet. Die Gütekriterien werden über alle Iterationen gemittelt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-29"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-29-1"><a href="#annotated-cell-29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Daten und benötigte Pakete laden</span></span>
<span id="annotated-cell-29-2"><a href="#annotated-cell-29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="annotated-cell-29-3"><a href="#annotated-cell-29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="annotated-cell-29-4"><a href="#annotated-cell-29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-29-5"><a href="#annotated-cell-29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Kreuzvalidierung mit 5 Folds</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-29" data-target-annotation="1">1</button><span id="annotated-cell-29-6" class="code-annotation-target"><a href="#annotated-cell-29-6" aria-hidden="true" tabindex="-1"></a>cv_control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">5</span>)</span>
<span id="annotated-cell-29-7"><a href="#annotated-cell-29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-29-8"><a href="#annotated-cell-29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Training des multiplen Regressionsmodells mit Kreuzvalidierung</span></span>
<span id="annotated-cell-29-9"><a href="#annotated-cell-29-9" aria-hidden="true" tabindex="-1"></a>cv_model <span class="ot">&lt;-</span> <span class="fu">train</span>(            </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-29" data-target-annotation="2">2</button><span id="annotated-cell-29-10" class="code-annotation-target"><a href="#annotated-cell-29-10" aria-hidden="true" tabindex="-1"></a>    mpg <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> cyl,</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-29" data-target-annotation="3">3</button><span id="annotated-cell-29-11" class="code-annotation-target"><a href="#annotated-cell-29-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> mtcars,</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-29" data-target-annotation="4">4</button><span id="annotated-cell-29-12" class="code-annotation-target"><a href="#annotated-cell-29-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-29" data-target-annotation="5">5</button><span id="annotated-cell-29-13" class="code-annotation-target"><a href="#annotated-cell-29-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">trControl =</span> cv_control</span>
<span id="annotated-cell-29-14"><a href="#annotated-cell-29-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-29-15"><a href="#annotated-cell-29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-29-16"><a href="#annotated-cell-29-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Ergebnisse anzeigen</span></span>
<span id="annotated-cell-29-17"><a href="#annotated-cell-29-17" aria-hidden="true" tabindex="-1"></a>cv_model</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-29" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-29" data-code-lines="6" data-code-annotation="1"><code>cv_control</code>: Definiert die Kreuzvalidierung mit 5 Folds.</span>
</dd>
<dt data-target-cell="annotated-cell-29" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-29" data-code-lines="10" data-code-annotation="2"><code>mpg ~ wt + hp + cyl</code>: Definiert die abhängige Variable (<code>mpg</code>) und die unabhängigen Variablen (<code>wt</code>, <code>hp</code>, <code>cyl</code>).</span>
</dd>
<dt data-target-cell="annotated-cell-29" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-29" data-code-lines="11" data-code-annotation="3"><code>data = mtcars</code>: Definiert den Datensatz, der für das Modelltraining verwendet wird.</span>
</dd>
<dt data-target-cell="annotated-cell-29" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-29" data-code-lines="12" data-code-annotation="4"><code>method = "lm"</code>: Definiert das Regressionsmodell als lineare Regression.</span>
</dd>
<dt data-target-cell="annotated-cell-29" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-29" data-code-lines="13" data-code-annotation="5"><code>trControl = cv_control</code>: Definiert die Kreuzvalidierung mit 5 Folds.</span>
</dd>
</dl>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

32 samples
 3 predictor

No pre-processing
Resampling: Cross-Validated (5 fold) 
Summary of sample sizes: 24, 24, 28, 26, 26 
Resampling results:

  RMSE      Rsquared   MAE     
  2.536794  0.8652719  2.134368

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
</div>
</section>
<section id="ergebnisse-der-kreuzvalidierung" class="level5">
<h5 class="anchored" data-anchor-id="ergebnisse-der-kreuzvalidierung">Ergebnisse der Kreuzvalidierung</h5>
<p>Nach der Durchführung der Kreuzvalidierung liefert das Modell folgende Kennwerte:</p>
<ul>
<li><p><strong>RMSE (Root Mean Squared Error):</strong> 2.537<br>
Der <strong>RMSE</strong> misst den durchschnittlichen quadratischen Fehler der Vorhersagen. Ein niedriger Wert deutet auf eine gute Modellanpassung hin.</p></li>
<li><p><strong><span class="math inline">\(R^2\)</span> (Bestimmtheitsmass):</strong> 0.865<br>
Der <strong><span class="math inline">\(R^2\)</span>-Wert</strong> zeigt, wie viel der Varianz von <code>mpg</code> durch die Prädiktoren <code>wt</code>, <code>hp</code> und <code>cyl</code> erklärt werden kann. Werte nahe 1 deuten auf eine hohe Erklärungskraft des Modells hin.</p></li>
<li><p><strong>MAE (Mean Absolute Error):</strong> 2.134<br>
Der <strong>MAE</strong> misst den durchschnittlichen absoluten Vorhersagefehler. Im Gegensatz zum RMSE ist er weniger empfindlich gegenüber Ausreissern.</p></li>
</ul>
</section>
<section id="interpretation-der-ergebnisse" class="level5">
<h5 class="anchored" data-anchor-id="interpretation-der-ergebnisse">Interpretation der Ergebnisse</h5>
<p>Das Modell zeigt folgende Leistungswerte:</p>
<ul>
<li><strong>Vorhersagegenauigkeit (RMSE):</strong> Der RMSE beträgt 2.537.
<ul>
<li>Ein RMSE &lt; 3 deutet auf eine <strong>gute Anpassung</strong> des Modells hin.<br>
</li>
<li>Werte &gt; 5 würden auf eine <strong>ungenügende Modellanpassung</strong> hindeuten.<br>
</li>
<li>In diesem Fall ist der Wert zufriedenstellend.</li>
</ul></li>
<li><strong>Erklärte Varianz (<span class="math inline">\(R^2\)</span>):</strong> Der <span class="math inline">\(R^2\)</span>-Wert beträgt 0.865.
<ul>
<li>Ein <span class="math inline">\(R^2\)</span> &gt; 0.7 gilt als <strong>sehr gut</strong>, da mehr als 70 % der Varianz von <code>mpg</code> durch die Prädiktoren erklärt wird.<br>
</li>
<li>Ein Wert &lt; 0.5 würde darauf hindeuten, dass das Modell wichtige Prädiktoren vermissen könnte.<br>
</li>
<li>Hier zeigt der Wert eine starke Erklärungskraft.</li>
</ul></li>
<li><strong>Durchschnittlicher Fehler (MAE):</strong> Der MAE beträgt 2.134.
<ul>
<li>Ein MAE &lt; 3 deutet darauf hin, dass die <strong>durchschnittlichen Vorhersagefehler gering</strong> sind.<br>
</li>
<li>Werte &gt; 5 könnten auf <strong>systematische Fehler</strong> im Modell hinweisen.<br>
</li>
<li>In unserem Fall ist der Fehler akzeptabel.</li>
</ul></li>
</ul>
</section>
<section id="fazit" class="level5">
<h5 class="anchored" data-anchor-id="fazit">Fazit</h5>
<p>Das multiple Regressionsmodell erklärt einen grossen Anteil der Varianz von <code>mpg</code> und liefert eine präzise Vorhersage. Die Kreuzvalidierung zeigt, dass das Modell auch bei unbekannten Daten <strong>stabile Ergebnisse</strong> liefert. Eventuelle Optimierungen könnten durch die Einbeziehung weiterer Prädiktoren oder Interaktionsterme erreicht werden.</p>
</section>
</div>
</div>
</div>
</section>
</section>
<section id="f-test" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="f-test"><span class="header-section-number">10.4.2</span> F-Test</h3>
<p>Der F-Test ist ein Hypothesentest, der die Güte des Regressionsmodells als Ganzes überprüft.</p>
<p><span class="math display">\[
F = \frac{\frac{R^2}{k}}{\frac{1-R^2}{n-(k+1)}} = \frac{\text{erklärte Varianz}}{\text{unerklärte Varianz}}
\]</span></p>
<ul>
<li><span class="math inline">\(R^2\)</span> ist das multiple Bestimmtheitsmass</li>
<li><span class="math inline">\(k\)</span> ist die Anzahl der unabhängigen Variablen</li>
<li><span class="math inline">\(n\)</span> ist die Anzahl der Beobachtungen</li>
</ul>
<p>Der F-Wert sagt, ob das Modell besser ist als einfach die Annahme des Mittelwerts von <span class="math inline">\(Y\)</span> zu nehmen. D.h. ob</p>
<p><span class="math display">\[
H_0 : R^2 = 0
\]</span></p>
<p>abgelehnt werden kann.</p>
<!---


#### Erste (zufällige) Anpassung

Im ersten Schritt betrachten wir eine **zufällige Regressionsgerade**, die mit grosser Wahrscheinlichkeit nicht gut zu den Daten passt. Die **Residuen** (grüne Linien) zeigen die Abstände zwischen den Datenpunkten und der Linie.



::: {.cell}

```{.r .cell-code  code-fold="true"}
# Setzen des Seeds für reproduzierbare Ergebnisse
set.seed(42)

# Definieren der Farbe mit Opacity
dot_color <- rgb(0, 0, 1, alpha = 0.6)
line_color <- rgb(0, 0, 1, alpha = 0.8)
residual_color <- rgb(0.87, 0.72, 0.53, alpha = 0.5)

x <- rnorm(30, mean = 10, sd = 2)
y <- 2 * x + rnorm(30, mean = 0, sd = 4)

plot(x, y, pch = 19, col = dot_color, xlab = "x", ylab = "y")
abline(a = 20, b = -0.5, col = line_color, lwd = 2)
for (i in 1:length(x)) {
  segments(x[i], y[i], x[i], -0.5 * x[i] + 20, col = residual_color, lwd = 1.5)
}

# Gesamtlänge der Residuen berechnen und anzeigen
residual_sum_random <- sum(abs(y - (-0.5 * x + 20)))
text(min(x), max(y), labels = paste("Residuen:", round(residual_sum_random, 2)), pos = 4, col = "blue2")
```

::: {.cell-output-display}
![Erster Ansatz: wir zeichnen eine beliebige Gerade und visualisieren die Residuen](regression_files/figure-html/random-line-1.png){width=672}
:::
:::



#### Logischer Verbesserungsschritt: Linie durch den Schwerpunkt

Statt zufällig eine bessere Linie zu raten, machen wir den **logischen ersten Schritt**: Wir zeichnen eine **horizontale Linie durch den Schwerpunkt der Daten**, d.h. die **Mittelwerte von $x$ und $y$**.

**Wichtige Erkenntnis:** Jede Regressionsgerade verläuft durch den Punkt $(\bar{x}, \bar{y})$.



::: {.cell}

```{.r .cell-code  code-fold="true"}
library(latex2exp)

mean_x <- mean(x)
mean_y <- mean(y)

plot(x, y, pch = 19, col = dot_color, xlab = "x", ylab = "y")
abline(h = mean_y, col = line_color, lwd = 2)
points(mean_x, mean_y, pch = 19, col = "red", cex = 1.5)
text(mean_x, mean_y, labels = TeX("$(\\bar{x}, \\bar{y})$"), pos = 4, col = "red")
for (i in 1:length(x)) {
  segments(x[i], y[i], x[i], mean_y, col = residual_color, lwd = 1.5)
}

# Gesamtlänge der Residuen berechnen und anzeigen
residual_sum_mean <- sum(abs(y - mean_y))
text(min(x), max(y), labels = paste("Residuen:", round(residual_sum_mean, 2)), pos = 4, col = "blue2")
```

::: {.cell-output-display}
![Zweiter Schritt: Wir zeichnen eine horizontale Linie durch den Schwerpunkt der Daten](regression_files/figure-html/mean-line-1.png){width=672}
:::
:::



#### Optimale Regressionsgerade (Least Squares)

Im letzten Schritt berechnen wir die **optimale Regressionsgerade** mithilfe der Methode der kleinsten Quadrate. Diese minimiert die Summe der quadrierten Abweichungen (Residuen).

::: {.callout-note collapse=true}
##### Schrittweise Herleitung

1. **Modellgleichung:**

Das lineare Regressionsmodell lautet:

$$
\hat{y} = \widehat{\beta_0} + \widehat{\beta_1} \cdot x
$$

- Das Dach $\widehat{\beta_0}$ und $\widehat{\beta_1}$ bedeutet, dass es sich um Schätzwerte handelt.

2. **Definition der Fehler (Residuen):**

Für jeden Datenpunkt ergibt sich das Residuum als Differenz zwischen dem beobachteten Wert $y_i$ und dem vorhergesagten Wert $\hat{y}_i$:

$$
e_i = y_i - (\widehat{\beta_0} + \widehat{\beta_1} x_i)
$$

3. **Zielfunktion – Summe der quadrierten Residuen (RSS):**

Wir wollen die Summe der quadrierten Residuen minimieren:

$$
RSS = \sum_{i=1}^{n} (y_i - (\widehat{\beta_0} + \widehat{\beta_1} x_i))^2
$$

4. **Optimierung durch partielle Ableitung:**

Wir minimieren $RSS$, indem wir die partiellen Ableitungen nach $\beta_0$ und $\beta_1$ berechnen und gleich null setzen:

- **Ableitung nach $\beta_0$:**

$$
\frac{\partial RSS}{\partial \widehat{\beta_0}} = -2 \sum (y_i - \widehat{\beta_0} - \widehat{\beta_1} x_i) = 0
$$

- **Ableitung nach $\beta_1$:**

$$
\frac{\partial RSS}{\partial \widehat{\beta_1}} = -2 \sum x_i (y_i - \widehat{\beta_0} - \widehat{\beta_1} x_i) = 0
$$

5. **Lösen des Gleichungssystems:**

Durch Umformen der beiden Gleichungen erhalten wir die sogenannten **Normalgleichungen**:

$$
\begin{aligned}
\sum y_i &= n \widehat{\beta_0} + \widehat{\beta_1} \sum x_i \\
\sum x_i y_i &= \widehat{\beta_0} \sum x_i + \widehat{\beta_1} \sum x_i^2
\end{aligned}
$$

6. **Endformeln für die Regressionskoeffizienten:**

Nach weiteren Umformungen ergeben sich die optimalen Schätzwerte für $\widehat{\beta_1}$ und $\widehat{\beta_0}$:

- **Steigung:**

$$
\widehat{\beta_1} = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2}
$$

- **Achsenabschnitt:**

$$
\widehat{\beta_0} = \bar{y} - \widehat{\beta_1} \cdot \bar{x}
$$

:::




::: {.cell}

```{.r .cell-code  code-fold="true"}
model <- lm(y ~ x)

plot(x, y, pch = 19, col = dot_color, xlab = "x", ylab = "y")
abline(model, col = line_color, lwd = 2)
for (i in 1:length(x)) {
  segments(x[i], y[i], x[i], predict(model)[i], col = residual_color, lwd = 1.5)
}

# Gesamtlänge der Residuen berechnen und anzeigen
residual_sum_optimal <- sum(abs(y - predict(model)))
text(min(x), max(y), labels = paste("Residuen:", round(residual_sum_optimal, 2)), pos = 4, col = "blue2")
```

::: {.cell-output-display}
![Dritter Schritt: Optimale Regressionsgerade (Methode der kleinsten Quadrate)](regression_files/figure-html/optimal-line-1.png){width=672}
:::
:::



-->


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/quanti\.baets\.ch\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./korrelation.html" class="pagination-link" aria-label="Korrelation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Korrelation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./fehlermasse.html" class="pagination-link" aria-label="Fehlermasse">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Fehlermasse</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Quantitative Methoden</p>
</div>   
    <div class="nav-footer-center">
<p>Made with ❤️ by <a href="https://lukasbatschelet.ch/">Lukas Batschelet</a></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/lbatschelet/quantitative_methoden/edit/main/regression.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li><li><a href="https://github.com/lbatschelet/quantitative_methoden/issues/new?assignees=lbatschelet&amp;labels=bug%2C+enhancement&amp;projects=&amp;template=bug_report.md&amp;title=%5BChapter%5D+Brief+description+of+the+issue+or+suggestion" class="toc-action"><i class="bi empty"></i>Problem melden</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://ko-fi.com/lukasbatschelet">☕️Buy me a coffee</a></p>
</div>
  </div>
</footer>




</body></html>